name = "Zen"
description = "A port of the Drupal zen base theme with libsass and gulp support."
homepage = "https://github.com/frjo/hugo-theme-zen"
license = "GPLv2"
licenselink = "http://www.gnu.org/licenses/old-licenses/gpl-2.0.html"
tags = ["simple", "articles"]
features = ["responsive", "grid", "sass", "gulp", "search"]
min_version = 0.18

[author]
  name = "Fredrik Jonsson"
  homepage = "https://xdeb.net/"

[original]
  name = "Drupal zen base theme"
  homepage = "https://www.drupal.org/project/zen"
  repo = "http://drupalcode.org/zen"

